@startuml

MasterMind *-- Board
MasterMind *-- "2" Player
MasterMind *-- Turn

Turn *-- CodeBreaker
Turn *-- CodeMaker

CodeBreaker -u-|> Player
    CodeBreaker --> TryCode
CodeMaker -u-|> Player
    CodeMaker --> SecretCode
    CodeMaker ..> CodeResult

Board *-- SecretCode
Board *-- "12" TryCode
Board *-- "12" CodeResult

SecretCode --|> Code
TryCode --|> Code

CodeResult *-- "n<5" Black
CodeResult *-- "1..5-n" White
    Black --|> ResultColor 
    White --|> ResultColor 

Code *-- "5" CodeColor
    Red -u-|> CodeColor
    Blue -u-|> CodeColor
    Green -u-|> CodeColor
    Yellow -u-|> CodeColor
    Pink -u-|> CodeColor
    Brown -u-|> CodeColor

@enduml